name: saige
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  firebase_auth: ^0.18.1
  firebase_image: ^0.2.0
  animated_splash_screen: ^1.0.1+2
  animations: ^1.1.2
  font_awesome_flutter: ^8.11.0
  google_fonts: ^1.1.1
  image_picker: ^0.6.7+17
  provider: ^4.3.2+4
  flutter_credit_card: ^0.1.3
  stripe_payment: ^1.0.9
  http: ^0.12.2
  cool_alert: ^1.0.1
  uuid: ^2.2.2
  flutter_spinkit: ^4.1.2+1
  auto_size_text: ^2.1.0
  flutter_phone_direct_caller: ^1.0.1
  url_launcher: ^5.7.10
  mailto: ^1.1.0
  mailer: ^3.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/saige_logo.png
    - assets/dev.png
    - assets/agro.png
    - assets/idee.png
    - assets/in.png
    - assets/infra.png
    - assets/dol.png
    - assets/a_propos.png
    - assets/compte.png
    - assets/plan.png
    - assets/projet.png
    - assets/cate.png
    - assets/inves.png
    - assets/default_project.png
    - assets/images/
    - assets/projects/
    - assets/error.png
    - assets/connection.png
    - assets/no_data.png
    - assets/radial_scale.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
